### ISSUE TITLE
有考虑针对包含NPU的SoC进行优化吗，比如rockchip的芯片？

### ISSUE THREAD

**Issue by shivabohemian** [midea-ai/Aidget#1]

**Comment by aidget** [comment]
你好，欢迎关注Aidget :)

Aidget推理框架主要针对于中低端的边端芯片，尤其是在内存及计算资源受限场景能够发挥出色的表现。

如果模型规模较大，建议尝试一下Aidget的`Compressor`模块进行模型压缩后再进行部署；
rockchip的芯片的话，可以尝试使用`RKNN-Toolkit`。

祝好
