### ISSUE TITLE
yolov7_ResRep训练后剪枝报错

### ISSUE THREAD

**Issue by 827238158** [midea-ai/Aidget#2]
我使用YOLOv7剪枝时遇到如下报错，具体位置在yolo.py中class Detect的forward函数里，这块是yolo原本就有的，各位大佬我该如何解决这个问题完成剪枝呢
Aidget\compressor\examples\pruning\YOLOv7\models\yolo.py:52: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4]:

**Comment by aidget** [comment]
> 

可以提供下你使用的pytorch版本 出错的 yolo.py 以及完整的错误日志吗？我们这边复现没有遇到这个错误

> 我使用YOLOv7剪枝时遇到如下报错，具体位置在yolo.py中class Detect的forward函数里，这块是yolo原本就有的，各位大佬我该如何解决这个问题完成剪枝呢 Aidget\compressor\examples\pruning\YOLOv7\models\yolo.py:52: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs! if self.grid[i].shape[2:4] != x[i].shape[2:4]:

**Comment by 827238158** [comment]
完整报错：
(pytorch38) E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7>python D_Resrep_prune.py --original_model weights/yolov7.pt --wrapped_model runs/train/resrep_train/weights/best.pt --img_size 640 --threshold 1e-4 --factor 8

 {'wrapped_model': 'runs/train/resrep_train/weights/best.pt', 'original_model': 'weights/yolov7.pt', 'img_size': 640, 'factor': 8, 'threshold': 0.0001} 

['E:\\pw_project\\prune&distill\\Aidget\\compressor\\examples\\pruning\\YOLOv7', 'D:\\Anaconda\\envs\\pytorch38\\python38.zip', 'D:\\Anaconda\\envs\\pytorch38\\DLLs', 'D:\\Anaconda\\envs\\pytorch38\\lib', 'D:\\Anaconda\\envs\\pytorch38', 'C:\\Users\\AQCJ\\AppData\\Roaming\\Python\\Python38\\site-packages', 'D:\\Anaconda\\envs\\pytorch38\\lib\\site-packages', 'E:/pw_project/prune&distill/Aidget/compressor', 'E:\\pw_project\\prune&distill\\Aidget\\compressor\\examples\\pruning']
Fusing layers... 
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register count_normalization() for <class 'torch.nn.modules.batchnorm.BatchNorm2d'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.pooling.MaxPool2d'>.
[INFO] Register count_upsample() for <class 'torch.nn.modules.upsampling.Upsample'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.container.Sequential'>.
Start pruning...
[INFO] Register count_convNd() for <class 'torch.nn.modules.conv.Conv2d'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.pooling.MaxPool2d'>.
[INFO] Register count_upsample() for <class 'torch.nn.modules.upsampling.Upsample'>.
[INFO] Register zero_ops() for <class 'torch.nn.modules.container.Sequential'>.
==> FLOPs Pruned Percent: 1.84% 53.236G ---> 52.257G
==> Params Pruned Percent: 1.90% 37.620M ---> 36.905M
E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7\models\yolo.py:55: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.grid[i].shape[2:4] != x[i].shape[2:4]:

>pytorch版本是1.8.1的，刚刚看了下要求版本是1.12以上，我再试试不同版本。出错的yolo.py就是pruning/YOLOv7/models/目录下的源码

**Comment by 827238158** [comment]
(pytorch_new) E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7>python D_Resrep_train.py --batch-size 10 --data data/coco128.yaml --cfg cfg/training/yolov7.yaml --weights weights/yolov7.pt --name resrep_train --hyp data/hyp.scratch.p5.yaml --epochs 400 --img-size 640

你们复现的pytorch版本是多少呀，我试了1.12没有办法进行训练和剪枝

Traceback (most recent call last):
  File "D_Resrep_train.py", line 681, in <module>
    train(hyp, opt, device, tb_writer)
  File "D_Resrep_train.py", line 126, in train
    ResRep_object.original_flops = calculate_model_flops(model, dummy_input, ResRep_object)
  File "E:\pw_project/prune&distill/Aidget/compressor\mslim\algorithms\pytorch\prune\Resrep_pruner.py", line 394, in calculate_model_flops
    modified_model.float().cuda()(dummy_input)
  File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7\models\yolo.py", line 604, in forward    
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7\models\yolo.py", line 630, in forward_once
    x = m(x)  # run
  File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\upsampling.py", line 154, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

**Comment by aidget** [comment]
> 

recompute_scale_factor是知名的conda里torch的bug，这个上网搜一下很容易找到解决方案的。另外warning不等于error，你都走到prune了，应该没有问题。你把if self.grid ！= x:  冒号后的东西也发出来看一下吧:)

**Comment by aidget** [comment]
> (pytorch_new) E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7>python D_Resrep_train.py --batch-size 10 --data data/coco128.yaml --cfg cfg/training/yolov7.yaml --weights weights/yolov7.pt --name resrep_train --hyp data/hyp.scratch.p5.yaml --epochs 400 --img-size 640
> 
> 你们复现的pytorch版本是多少呀，我试了1.12没有办法进行训练和剪枝
> 
> Traceback (most recent call last): File "D_Resrep_train.py", line 681, in train(hyp, opt, device, tb_writer) File "D_Resrep_train.py", line 126, in train ResRep_object.original_flops = calculate_model_flops(model, dummy_input, ResRep_object) File "E:\pw_project/prune&distill/Aidget/compressor\mslim\algorithms\pytorch\prune\Resrep_pruner.py", line 394, in calculate_model_flops modified_model.float().cuda()(dummy_input) File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7\models\yolo.py", line 604, in forward return self.forward_once(x, profile) # single-scale inference, train File "E:\pw_project\prune&distill\Aidget\compressor\examples\pruning\YOLOv7\models\yolo.py", line 630, in forward_once x = m(x) # run File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\upsampling.py", line 154, in forward recompute_scale_factor=self.recompute_scale_factor) File "D:\Anaconda\envs\pytorch_new\lib\site-packages\torch\nn\modules\module.py", line 1207, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

具体可以参考 https://blog.csdn.net/qq_40280673/article/details/125095353

tracerwarning是正常现象不影响图搜索的，你看看目录下有没有生成 pruned_model.pt，应该是已经有了的

**Comment by 827238158** [comment]
感谢回复，recompute_scale_factor错误已解决 : )，确实在目录中已存在 pruned_model.pt。不过if self.grid[i].shape[2:4] != x[i].shape[2:4]:冒号后面没打印别的东西了，我三天前的comment就是完整的输出。
出现tracewarning会不会是因为我加载的剪枝训练模型有问题，我自己跑yolov5、v7代码从来没tracewarning

**Comment by aidget** [comment]
> 感谢回复，recompute_scale_factor错误已解决 : )，确实在目录中已存在 pruned_model.pt。不过if self.grid[i].shape[2:4] != x[i].shape[2:4]:冒号后面没打印别的东西了，我三天前的comment就是完整的输出。 出现tracewarning会不会是因为我加载的剪枝训练模型有问题，我自己跑yolov5、v7代码从来没tracewarning

正常的warning，忽略即可～
