### ISSUE TITLE
关于scratch from zero prune_training的疑惑

### ISSUE THREAD

**Issue by 827238158** [midea-ai/Aidget#3]
又继续学习Aidget模型压缩了

看了下剪枝的Markdown文件中给出的运行prune_training.py命令参数--weights ''，意思是从零训练吧。

上次走通剪枝+蒸馏baseline是用的yolov7官方预训练模型进行剪枝训练，今天想按照Markdown里的weights ''命令参数从0剪枝训练发现会报错。

原因是prune_training.py line125加载了不存在的opt.weights路径，我把这行注释了反正是可以正常训练了也不知道对不对
    model = torch.load(opt.weights, map_location=device)['model'].float().cuda()
    ResRep_object = ResRep(copy.deepcopy(model))        
    model = ResRep_object.wrapped_model

还有就是我自己是single_gpu剪枝训练的，代码save的是EMA model，EMA策略会不会使剪枝失效啊？

**Comment by 827238158** [comment]
(⊙o⊙)…呃写错了，，，是D_Resrep_train.py，不是prune_training.py

**Comment by aidget** [comment]
> 

注释掉之后就直接进行稀疏训练了 一般建议加载训练好的float模型再做稀疏训练 请仔细检查传入的权重pt名称是否跟训练好的float模型名称一致

**Comment by aidget** [comment]
> 又继续学习Aidget模型压缩了
> 
> 看了下剪枝的Markdown文件中给出的运行prune_training.py命令参数--weights ''，意思是从零训练吧。
> 
> 上次走通剪枝+蒸馏baseline是用的yolov7官方预训练模型进行剪枝训练，今天想按照Markdown里的weights ''命令参数从0剪枝训练发现会报错。
> 
> 原因是prune_training.py line125加载了不存在的opt.weights路径，我把这行注释了反正是可以正常训练了也不知道对不对 model = torch.load(opt.weights, map_location=device)['model'].float().cuda() ResRep_object = ResRep(copy.deepcopy(model))         model = ResRep_object.wrapped_model
> 
> 还有就是我自己是single_gpu剪枝训练的，代码save的是EMA model，EMA策略会不会使剪枝失效啊？

注释掉之后就直接进行稀疏训练了 一般建议加载训练好的float模型再做稀疏训练 请仔细检查传入的权重pt名称是否跟训练好的float模型名称一致

**Comment by 827238158** [comment]
OKOK ：)
